import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";

export const metadata: Metadata = {
  title: "King County Explorer Search & Rescue",
  description: "Generated by create next app",
};
const mulish = Mulish({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const bodyClass = `flex flex-col h-screen ${mulish.className}`;
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link
          rel="stylesheet"
          href="https://use.typekit.net/xyo6wwn.css"
        ></link>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="shortcut icon" href="/kcesar/favicon.ico" />
      </head>
      <body className={bodyClass}>
        <Navbar />
          <div className="flex-1">
            {children}
          </div>
        <Footer />
      </body>
    </html>
  );
}
